#!/usr/bin/env bash
set -e

cd $(dirname $(realpath ${0}))

source config

git config --global user.email ${github_user_email}
git config --global user.name ${github_user_name}

mkdir ${HOME}/.ssh
touch ${HOME}/.ssh/config
cat <<EOF | tee ${HOME}/.ssh/config >&2 
Host github.com
    StrictHostKeyChecking no
EOF

#write out current crontab
crontab -l > cronjobs | true 

#echo new cron into cron file
if [[ ${commit_on_workday} -gt 0 ]]; then
    workday_frequency=$((24/${commit_on_workday}))
    echo ${workday_frequency}
    echo "* */${workday_frequency} * * 1-5 $(pwd)/updater 2>&1 >> /tmp/workday_log" >> cronjobs
fi

if [[ ${commit_on_weekend} -gt 0 ]]; then
    weekend_frequency=$((24/${commit_on_weekend}))
    echo ${weekend_frequency}
    echo "* */${weekend_frequency} * * 0,6 $(pwd)/updater 2>&1 >> /tmp/weekend_log" >> cronjobs
fi

#install new cron file
crontab cronjobs
rm cronjobs

rsyslogd
cron
touch /var/log/cron.log
tail -F /var/log/syslog /var/log/cron.log

