#!/usr/bin/env bash
set -e

cd $(dirname $(realpath ${0}))

source config

test_luck () {
    local luck=$(($RANDOM%10))
    echo ${luck}
    echo ${commit_likeliness}
    if [ "${luck}" -lt "$((10-$commit_likeliness))" ]; then
        echo "Not lucky enough"
        exit 0
    fi
}

request_random_quote () {
    local respond_body=$(curl -X POST 'https://andruxnet-random-famous-quotes.p.mashape.com/?cat=movies' \
                        -H "X-Mashape-Key: ${mashape_key}" \
                        -H 'Content-Type: application/x-www-form-urlencoded' \
                        -H 'Accept: application/json')

    quote=$(echo ${respond_body} | jq .quote | tr -d '"')
    author=$(echo ${respond_body} | jq .author | tr -d '"')

    echo ${quote:? "API Error"}
    echo ${author:? "API Error"}
}

generate_document () {
    echo $(source template) > index.html
}

push_changes () {
    eval $(ssh-agent -s)
    ssh-add ${github_ssh_key}
    local commit_message_count=${#commit_messages[*]}
    local this_commit=${commit_messages[$((RANDOM%commit_message_count))]}
    git pull origin gh-pages
    git add -A
    git commit -m "${this_commit}"
    git push origin gh-pages
}

main () {
    test_luck
    request_random_quote
    generate_document
    push_changes
}

main
